cheeses_dict = {
'Abondance Fermlere Herve Mons': 'American Cheese',
'American Cheese': 'American Cheese',
'Appenzeller': 'American Cheese',
'Areesh': 'American Cheese',
'Aura': 'American Cheese',
'Baramily': 'American Cheese',
'Bergenost': 'American Cheese',
'Blue cheese': 'American Cheese',
'Blue Cheese, Maytag': 'American Cheese',
'Maytag Blue Cheese': 'American Cheese',
'Borough Market Stilton': 'American Cheese',
'Brick Cheese': 'American Cheese',
'Brie': 'American Cheese',
'Brie Cheese': 'American Cheese',
'Cabot': 'American Cheese',
'Cahills Porter': 'American Cheese',
'Camembert cheese': 'American Cheese',
'Campode Montalban': 'American Cheese',
'Caravan cheese': 'American Cheese',
'Casein': 'American Cheese',
'Cheddar Cheese': 'American Cheese',
'Cheshire Cheese': 'American Cheese',
'Chloro': 'American Cheese',
'Cholera Cheese': 'American Cheese',
'Colby Cheese': 'American Cheese',
'Colby-Jack Cheese': 'American Cheese',
'Cordobes': 'American Cheese',
'Cottage Cheese, Full Fat': 'American Cheese',
'Cotija': 'American Cheese',
'Cottage Cheese': 'American Cheese',
'Full Fat Cottage Cheese': 'American Cheese',
'Cottage Cheese': 'American Cheese',
'Cottage cheese, Trim': 'American Cheese',
'Trim Cottage Cheese': 'American Cheese',
'Cougar Gold Cheddar': 'American Cheese',
'Cream Cheese': 'American Cheese',
'Cup Cheese': 'American Cheese',
'Domiati': 'American Cheese',
'Drunken Goat Cheese': 'American Cheese',
'Dublinger': 'American Cheese',
'Edam Cheese': 'American Cheese',
'Emmental Cheese': 'American Cheese',
'Emmenthal': 'American Cheese',
'Emmenthal Swiss Cheese': 'American Cheese',
'English Derby with Sage': 'American Cheese',
'Farmer Cheese': 'American Cheese',
'Feta': 'American Cheese',
'Feta Cheese': 'American Cheese',
'Fiscalim Sand Joaquin': 'American Cheese',
'Goat Cheese': 'American Cheese',
'Gorgonzola cheese': 'American Cheese',
'Gouda': 'American Cheese',
'Gouda Cheese': 'American Cheese',
'Government Cheese': 'American Cheese',
'Gran Queso': 'American Cheese',
'Gruyere Cheese': 'American Cheese',
'Half & Half': 'American Cheese',
'Halumi': 'American Cheese',
'Havarti': 'American Cheese',
'Havarti Cheese': 'American Cheese',
'Herve Cheese': 'American Cheese',
'Herve Mons Pave De Nord': 'American Cheese',
'Herve Mons Tomme Des Bois Noir': 'American Cheese',
'Istanboly': 'American Cheese',
'Jack, Monterey': 'American Cheese',
'Jarlsberg Cheese': 'American Cheese',
'Kefalotyri Cheese': 'American Cheese',
'Kefir': 'American Cheese',
'Kerrygold Invernia': 'American Cheese',
'Le Gruyere Switzerland': 'American Cheese',
'Liederkranz Cheese': 'American Cheese',
'Limburger Cheese': 'American Cheese',
'Manchego': 'American Cheese',
'Manchego 1 year': 'American Cheese',
'Manchego 8 mo. raw milk': 'American Cheese',
'Manchego Cheese': 'American Cheese',
'Mascarpone Cheese': 'American Cheese',
'Mimolette': 'American Cheese',
'Mish': 'American Cheese',
'Montasio': 'American Cheese',
'Monterey Jack Cheese': 'American Cheese',
'Mozzarella Cheese': 'American Cheese',
'Mozzarella': 'American Cheese',
'Muenster Cheese': 'American Cheese',
'Naked Goat': 'American Cheese',
'Neufchatel cheese': 'American Cheese',
'Paneer Cheese': 'American Cheese',
'Parmesan Cheese': 'American Cheese',
'Parmesan cheese': 'American Cheese',
'Parmigiano-Reggiano': 'American Cheese',
'Parmigiano-Reggiano Cheese': 'American Cheese',
'Pastore Sini': 'American Cheese',
'Pecorino Cheese': 'American Cheese',
'Pepper jack': 'American Cheese',
'Pepperjack Cheese': 'American Cheese',
'Pepper jack Cheese': 'American Cheese',
'Pimento Cheese': 'American Cheese',
'Pinconning Cheese': 'American Cheese',
'Plave': 'American Cheese',
'Port de Salut Cheese': 'American Cheese',
'Provel Cheese': 'American Cheese',
'Provolone Cheese': 'American Cheese',
'Provolone': 'American Cheese',
'Quark cheese': 'American Cheese',
'Ricotta Cheese': 'American Cheese',
'Romanian Urda': 'American Cheese',
'Romano Cheese': 'American Cheese',
'Roquefort Cheese': 'American Cheese',
'Roquefort': 'American Cheese',
'Rumi': 'American Cheese',
'Salad Dressings, creamy': 'American Cheese',
'Sheep Milk Cheeses': 'American Cheese',
'Sour Cream': 'American Cheese',
'Spray Cheese': 'American Cheese',
'Stilton Cheese': 'American Cheese',
'String Cheese': 'American Cheese',
'Swiss Cheese': 'American Cheese',
'Taleggio': 'American Cheese',
'Taleggio Cheese': 'American Cheese',
'Teleme Cheese': 'American Cheese',
'Tete de Moine': 'American Cheese',
'Ubriaco Del Plave PO-SI': 'American Cheese',
'Uniekaas Reserve': 'American Cheese',
'Uniekaas Robusto': 'American Cheese',
'Velveeta': 'American Cheese',
'Whey Protein Powder': 'American Cheese',
'White Cheeses': 'American Cheese',
'Yellow Cheeses': 'American Cheese',
'Asiago Cheese': 'American Cheese',
'cheese': 'American Cheese'

}