italian_substitutes_dict = {
    'skinless, boneless chicken breasts':'Italian sausage',
    'boneless, chicken breasts': 'Italian sausage', 
	'Asiago Cheese': 'mozzarella cheese',
	'Cheddar cheese': 'mozzarella cheese',
	'Monterey Jack cheese':'mozzarella cheese', 
	'provolone cheese': 'mozzarella cheese',
	'American cheese': 'mozzarella cheese',
	'Pepper jack cheese': 'mozzarella cheese',
	'chicken': 'Italian Sausage',
    'chicken breasts': 'Italian Sausage',
	'beef': 'Italian Sausage',
	'pork': 'Italian Sausage',
	'Sausage': 'Italian Sausage',
	'chicken breasts': 'Italian Sausage',
    'chicken breast': 'Italian Sausage',
	'French dressing': 'Italian dressing',
	'Caesar dressing': 'Italian dressing',
	'ranch dressing': 'Italian dressing',
	'balsamic dressing': 'Italian dressing',
    'Honey Mustard': 'Italian dressing',
    'Asian Ginger dressing': 'Italian dressing',
	'cheese': 'mozzarella cheese',
    'agar agar':'basil',
    'Allspice':'basil',
    'Anise Seed':'basil',
    'Apple Pie Spice':'basil',
    'Arrowroot':'basil',
    'Bar-B-Que Spice':'basil',
    'bbq spice':'basil',
    'Bay Leaf':'basil',
    'Cajun Spice':'basil',
    'Caraway Seed':'basil',
    'Cardamom':'basil',
    'Cayenne Pepper':'basil',
    'Celery Salt':'basil',
    'Chinese Five Spice':'basil',
    'Chipolte Pepper':'basil',
    'Chives':'basil',
    'Cilantro':'basil',
    'Cinnamon':'basil',
    'Cloves':'basil',
    'Coriander':'basil',
    'Cream Of Tartar':'basil',
    'Cumin':'basil',
    'Curry':'basil',
    'Dill':'basil',
    'Fajita Seasoning':'basil',
    'Fennel':'basil',
    'Fenugreek':'basil',
    'Garam Masala':'basil',
    'Garlic':'basil',
    'Ginger':'basil',
    'Grains F Paradise':'basil',
    'Gumbo File':'basil',
    'Herbs De Provence':'basil',
    'Hickory':'basil',
    'Salt':'basil',
    'Horseradish':'basil',
    'Lemon Pepper':'basil',
    'Mace':'basil',
    'Marjoram':'basil',
    'Mustard Seed':'basil',
    'Nutmeg':'basil',
    'Oregano':'basil',
    'Oriental Stir Fry Spice':'basil',
    'Paprika':'basil',
    'Parsley':'basil',
    'Pepper':'basil',
    'Pickling Spice':'basil',
    'Pizza Seasoning':'basil',
    'Poppy Seed':'basil',
    'Poultry Seasoning':'basil',
    'Pumpkin Pie Spice':'basil',
    'Rosemary':'basil',
    'Safflower':'basil',
    'Saffron':'basil',
    'Sage':'basil',
    'Salad Herbs':'basil',
    'Salt':'basil',
    'Savory':'basil',
    'Summer Leaf':'basil',
    'Taco Seasoning':'basil',
    'Tarragon':'basil',
    'Thai Seasoning':'basil',
    'Thyme':'basil',
    'Turmeric':'basil',
    'Vanilla Bean':'basil',
    'Turkey':'Italian Sausage',
    'Lamb':'Italian Sausage',
    'Bacon':'Italian Sausage',
    'Duck':'Italian Sausage',
    'Goat':'Italian Sausage',
    'Crab':'Italian Sausage',
    'Fish':'Italian Sausage',
    'Tilapia':'Italian Sausage',
    'Salmon': 'Italian Sausage',
    'Sea Bass':'Italian Sausage',
    'Bass':'Italian Sausage',
    'Rabbit':'Italian Sausage'

}